### ISSUE TITLE
OpenAI代理地址调不通

### ISSUE THREAD

**Issue by AllenPan03** [DAMO-NLP-SG/WebDesignAgent#10]
我在API工具上能正常调通，但在config设置之后，一直调不通
![image](https://github.com/DAMO-NLP-SG/WebDesignAgent/assets/11730845/419c8084-0684-4697-ad8d-ea80f29b4709)
![image](https://github.com/DAMO-NLP-SG/WebDesignAgent/assets/11730845/fcb63e5c-590a-400f-b8bf-89ec878f1db6)
![image](https://github.com/DAMO-NLP-SG/WebDesignAgent/assets/11730845/67892ab3-9184-4ed9-8e71-cd3e07f57f0e)

**Comment by jianghuyihei** [comment]
抱歉，您看起来用的是base_url来进行调用，这个我们忘记支持了,我会尽量在今天进行修复，你可以先直接在LLM.py里设置LLM，将运行配置设置成你需要的，或者是等待我们的更新，万分抱歉！

**Comment by jianghuyihei** [comment]
> 我在API工具上能正常调通，但在config设置之后，一直调不通 ![image](https://private-user-images.githubusercontent.com/11730845/345668087-419c8084-0684-4697-ad8d-ea80f29b4709.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTk2NzksIm5iZiI6MTcyMDA1OTM3OSwicGF0aCI6Ii8xMTczMDg0NS8zNDU2NjgwODctNDE5YzgwODQtMDY4NC00Njk3LWFkOGQtZWE4MGYyOWI0NzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAyMTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NGQ1ZDQ0ZmMyYTAxZGI2ZjcxYWQ5NzUwZGZkZWM5YzA0OWY3MzcwOGNlMmU4MmNlYTM1NDgyMWEyZmU0MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MArkUQeKpjGAEu9sQxzNWn7YZ48vKyAgeoWDQ-WLK04) ![image](https://private-user-images.githubusercontent.com/11730845/345668475-fcb63e5c-590a-400f-b8bf-89ec878f1db6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTk2NzksIm5iZiI6MTcyMDA1OTM3OSwicGF0aCI6Ii8xMTczMDg0NS8zNDU2Njg0NzUtZmNiNjNlNWMtNTkwYS00MDBmLWI4YmYtODllYzg3OGYxZGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAyMTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5MjVkZDRhMWZhZTU2NjM2NzQwNGQ0ODM1YTY3ZDgzMWQzNDE3MjkzZTg5NzAwOGZhNDY2YmE0NWJkM2IxMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y0WePfwWd3fxUBMS9rSfqiwRpjV3wBrPCWSnaGjnJvU) ![image](https://private-user-images.githubusercontent.com/11730845/345668937-67892ab3-9184-4ed9-8e71-cd3e07f57f0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTk2NzksIm5iZiI6MTcyMDA1OTM3OSwicGF0aCI6Ii8xMTczMDg0NS8zNDU2Njg5MzctNjc4OTJhYjMtOTE4NC00ZWQ5LThlNzEtY2QzZTA3ZjU3ZjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAyMTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNWIwM2Q5NzMxNGE0Y2ZlMGM5NDVmOWRiMTIzYWU1YmFkNzE2N2IxZTVkOGFhZDc2MjI3NWQ2ZTQ4NDQ4NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZaVz5jabrI0ELC3g42PotRpzgfw8sVCylTWuTyIdyv0)

抱歉，您看起来用的是base_url来进行调用，这个我们忘记支持了,我会尽量在今天进行修复，你可以先直接在LLM.py里设置LLM，将运行配置设置成你需要的，或者是等待我们的更新，万分抱歉！

**Comment by jianghuyihei** [comment]
> 我在API工具上能正常调通，但在config设置之后，一直调不通 ![image](https://private-user-images.githubusercontent.com/11730845/345668087-419c8084-0684-4697-ad8d-ea80f29b4709.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjAxNjEsIm5iZiI6MTcyMDA1OTg2MSwicGF0aCI6Ii8xMTczMDg0NS8zNDU2NjgwODctNDE5YzgwODQtMDY4NC00Njk3LWFkOGQtZWE4MGYyOWI0NzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAyMjQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMWVjNmFkZDNhZjY1YWQ0NWI1ZmZlNGZiZmM3NzU0OGE5Y2UwOTNmNzY1MmI0YTQwMjViNDI4ZDJiZjRmNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tIi35l9znHgGu-On5c2YlF-HfCTVR3jHI6V6TPf5cMY) ![image](https://private-user-images.githubusercontent.com/11730845/345668475-fcb63e5c-590a-400f-b8bf-89ec878f1db6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjAxNjEsIm5iZiI6MTcyMDA1OTg2MSwicGF0aCI6Ii8xMTczMDg0NS8zNDU2Njg0NzUtZmNiNjNlNWMtNTkwYS00MDBmLWI4YmYtODllYzg3OGYxZGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAyMjQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MTcxM2ZmZmMzYWM4NGNlYzhjYmIwNGEyYmU3YzBiNTllZDlkNjgwNjE4MTVjMjUwYjlhMTIxOGVmZmZkNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BJa9eJw5R11To7s4gm32lFxNMiltUGNRkORZUHhCphk) ![image](https://private-user-images.githubusercontent.com/11730845/345668937-67892ab3-9184-4ed9-8e71-cd3e07f57f0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjAxNjEsIm5iZiI6MTcyMDA1OTg2MSwicGF0aCI6Ii8xMTczMDg0NS8zNDU2Njg5MzctNjc4OTJhYjMtOTE4NC00ZWQ5LThlNzEtY2QzZTA3ZjU3ZjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAyMjQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZmMxMTEyN2YzMjE0MTZjZDFjNWM4MTM2NjBhODU3MWI3ODRjZTQxYjA5M2QzODk3ZjFlMzEwYWZmZjRiMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.02dul6mNdxruWGE8nay-olYSXcE-SBFFWQtba6BPy5g)

我们已经修复了这个问题，感谢您的发现，您可以重新clone下来重新尝试
