### ISSUE TITLE
生成页面时一直报Request timed out.

### ISSUE THREAD

**Issue by suepradun** [DAMO-NLP-SG/WebDesignAgent#11]
用gpt-4o测试了几次，都是出现能生成plan 。但是生成页面是报Request timed out。

能否增加些日志，容易看出是哪里报错。

![image](https://github.com/DAMO-NLP-SG/WebDesignAgent/assets/59818764/6a17a99b-3fd8-49e9-8161-08825faba7b5)

**Comment by jianghuyihei** [comment]
你试一下能用dalle3生成图片吗，看起来像是生成图片出现了问题

**Comment by jianghuyihei** [comment]
> 用gpt-4o测试了几次，都是出现能生成plan 。但是生成页面是报Request timed out。
> 
> 能否增加些日志，容易看出是哪里报错。
> 
> ![image](https://private-user-images.githubusercontent.com/59818764/345881924-6a17a99b-3fd8-49e9-8161-08825faba7b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDcxMDMsIm5iZiI6MTcyMDEwNjgwMywicGF0aCI6Ii81OTgxODc2NC8zNDU4ODE5MjQtNmExN2E5OWItM2ZkOC00OWU5LTgxNjEtMDg4MjVmYWJhN2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDE1MjY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMzIzNmYzMmI3YjRiYzM4NDkxZGI5NTZjODZjNGQ1MjhjMWQ0NzIxMzZjNTM1M2ZhYzQyZmI5ZGZhZjU0MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xJ1pDKIZhu-2pYfp5CAAhHKPKT0MSVSTOaUxcjurWZ4)

你试一下能用dalle3生成图片吗，看起来像是生成图片出现了问题

**Comment by jianghuyihei** [comment]
> 用gpt-4o测试了几次，都是出现能生成plan 。但是生成页面是报Request timed out。
> 
> 能否增加些日志，容易看出是哪里报错。
> 
> ![image](https://private-user-images.githubusercontent.com/59818764/345881924-6a17a99b-3fd8-49e9-8161-08825faba7b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDcyNTAsIm5iZiI6MTcyMDEwNjk1MCwicGF0aCI6Ii81OTgxODc2NC8zNDU4ODE5MjQtNmExN2E5OWItM2ZkOC00OWU5LTgxNjEtMDg4MjVmYWJhN2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDE1MjkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NzQ2NzJiNGU0NTlhMDJjNjhjOTU3MTVkNjk4YTYxYTVhMWM1ZmUxMzY2NWU2ZmE5YzNjODA0YzNjMzUzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LtwPFaK-sX7AfIjVHXbhuw6X8j0nG6NKueDqdiREWnk)

我之后会进行一定的报错补充，谢谢你的提醒

**Comment by suepradun** [comment]
不生成图片也会调用dalle3么？  我要换个账号测试，手头这个号没开会员。
![image](https://github.com/DAMO-NLP-SG/WebDesignAgent/assets/59818764/54d07cdb-30d0-4fe3-a6b7-0e3aaf5e961b)

**Comment by jianghuyihei** [comment]
> 不生成图片也会调用dalle3么？ 我要换个账号测试，手头这个号没开会员。 ![image](https://private-user-images.githubusercontent.com/59818764/345886800-54d07cdb-30d0-4fe3-a6b7-0e3aaf5e961b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDgwMTYsIm5iZiI6MTcyMDEwNzcxNiwicGF0aCI6Ii81OTgxODc2NC8zNDU4ODY4MDAtNTRkMDdjZGItMzBkMC00ZmUzLWE2YjctMGUzYWFmNWU5NjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDE1NDE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYmMxMTI0OWRjMDFiZGYxYzkyYjI2MDU5YTMyYzM1ZTk3NDc5NDFhNGNmOTg3ZmI3Zjg5ODZmZGQ1ZTUzYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xZkN7sr23UaOOji5cxpYLkdY_1ltJO09F7OCW_VXxSY)

那应该不会调用，你看一下save file那有html生成吗

**Comment by jianghuyihei** [comment]
> 不生成图片也会调用dalle3么？ 我要换个账号测试，手头这个号没开会员。 ![image](https://private-user-images.githubusercontent.com/59818764/345886800-54d07cdb-30d0-4fe3-a6b7-0e3aaf5e961b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDgwMTYsIm5iZiI6MTcyMDEwNzcxNiwicGF0aCI6Ii81OTgxODc2NC8zNDU4ODY4MDAtNTRkMDdjZGItMzBkMC00ZmUzLWE2YjctMGUzYWFmNWU5NjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDE1NDE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYmMxMTI0OWRjMDFiZGYxYzkyYjI2MDU5YTMyYzM1ZTk3NDc5NDFhNGNmOTg3ZmI3Zjg5ODZmZGQ1ZTUzYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xZkN7sr23UaOOji5cxpYLkdY_1ltJO09F7OCW_VXxSY)

你可以先尝试一下右边的gen website生成单个页面试试，感觉这个看起来像是openai那边的问题，网络有点问题

**Comment by jianghuyihei** [comment]
> 用gpt-4o测试了几次，都是出现能生成plan 。但是生成页面是报Request timed out。
> 
> 能否增加些日志，容易看出是哪里报错。
> 
> ![image](https://private-user-images.githubusercontent.com/59818764/345881924-6a17a99b-3fd8-49e9-8161-08825faba7b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjMxNDEsIm5iZiI6MTcyMDE2Mjg0MSwicGF0aCI6Ii81OTgxODc2NC8zNDU4ODE5MjQtNmExN2E5OWItM2ZkOC00OWU5LTgxNjEtMDg4MjVmYWJhN2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA3MDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MDZhY2M1YTk5ZjU5YTNlOTg5MTZkMTYyNWNlNzZkZmUxMTc5MDYyNzBkY2U3ZDU3ZDg0ZGY4MTk1ZjY3YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3_6GgpOTF1p7J92zuHTx2U3s7axGOeByX-SXkALgQS8)

已经增添了一些日志
