### ISSUE TITLE
I hope to add more LLms models

### ISSUE THREAD

**Issue by redpintings** [DAMO-NLP-SG/WebDesignAgent#12]
Because I find it difficult to use OpenAi and Claude Api in China, which is a great project and a great job, I hope to support some models such as Yi, ChatGLM, or deepseek. thank you

**Comment by jianghuyihei** [comment]
> Because I find it difficult to use OpenAi and Claude Api in China, which is a great project and a great job, I hope to support some models such as Yi, ChatGLM, or deepseek. thank you

Thank you for your suggestion. We have updated the version and now support chatglm.
