### ISSUE TITLE
使用glm 模型，无法生成plan文件

### ISSUE THREAD

**Issue by suepradun** [DAMO-NLP-SG/WebDesignAgent#13]
![image](https://github.com/DAMO-NLP-SG/WebDesignAgent/assets/59818764/2bba56c1-ba30-4339-bf45-e677ee984309)

试了几次都没生成。

**Comment by jianghuyihei** [comment]
> ![image](https://private-user-images.githubusercontent.com/59818764/346166095-2bba56c1-ba30-4339-bf45-e677ee984309.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTMxNzIsIm5iZiI6MTcyMDE5Mjg3MiwicGF0aCI6Ii81OTgxODc2NC8zNDYxNjYwOTUtMmJiYTU2YzEtYmEzMC00MzM5LWJmNDUtZTY3N2VlOTg0MzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDE1MjExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2OTc1ZWRlNzE3Nzk3NjMxNTEyZWZkYmExYmUxNTU1NjhhYThmMGY3ZTQxOTZkYTg0MTEwYmE1YWZjMzdjYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1gS72I0-AJua636gGix1aetKymZrByzMVAc1oL-vy7E)
> 
> 试了几次都没生成。

你可以把他生成失败的response发一下吗，这应该就是glm的模型指令跟随能力不强，导致没有parse出来，我并没有针对glm做专门的调优，这可能需要花点时间，我之后会尽力解决这个问题

**Comment by jianghuyihei** [comment]
> ![image](https://private-user-images.githubusercontent.com/59818764/346166095-2bba56c1-ba30-4339-bf45-e677ee984309.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MTA2MDYsIm5iZiI6MTcyMDQxMDMwNiwicGF0aCI6Ii81OTgxODc2NC8zNDYxNjYwOTUtMmJiYTU2YzEtYmEzMC00MzM5LWJmNDUtZTY3N2VlOTg0MzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAzNDUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZjhkOGZlNzc5ZjRmZjRiNmM0Nzg3NTY3OWQ4OGU2MzliZmFhNjdlOTY1MWUzNWM4N2U1MDEyMzExNTgzMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-GIxXbBSV93xVfs-V9IrV6ojI2t48yH1_8SbM-sNd_0)
> 
> 试了几次都没生成。

原因是因为glm-4v 输出的token有限制，目前已经解决了这个问题
