### ISSUE TITLE
请考虑支持下硅基的SD3出图

### ISSUE THREAD

**Issue by suepradun** [DAMO-NLP-SG/WebDesignAgent#16]
# 硅基流动的
import requests

url = "https://api.siliconflow.cn/v1/stabilityai/stable-diffusion-3-medium/text-to-image"

payload = {
    "prompt": "Studio Ghibli style, Ghibli color, anime style illustration, A couple is dancing a waltz on the rooftop of a high-rise building in the city in the rain. They are dressed in gorgeous dance clothes, with the shimmering city night scene behind them. Raindrops fall on the roof, reflecting romantic lights. The background is a city on a rainy night",
    "image_size": "1024x1024",
    "batch_size": 1,
    "num_inference_steps": 20,
    "guidance_scale": 7
}
headers = {
    "accept": "application/json",
    "content-type": "application/json",
    "authorization": "Bearer <key>"
}

response = requests.post(url, json=payload, headers=headers)
print(response.text)
image_url = response.json()["images"][0]["url"]

**Comment by jianghuyihei** [comment]
> # 硅基流动的
> 导入请求
> 
> url =“ https://api.siliconflow.cn/v1/stabilityai/stable-diffusion-3-medium/text-to-image ”
> 
> payload = { "prompt": "吉卜力工作室风格，吉卜力色彩，动漫风格插画，一对情侣在雨中在城市高楼楼顶跳着华尔兹，他们穿着华丽的舞衣，身后是波光粼粼的城市夜景，雨滴落在屋顶上，反射出浪漫的灯光，背景是雨夜的城市", "image_size": "1024x1024", "batch_size": 1, "num_inference_steps": 20, "guidance_scale": 7 } headers = { "accept": "application/json", "content-type": "application/json", "authorization": "Bearer " }
> 
> 响应 = 请求.post（url，json = payload，headers = headers） 打印（response.text） image_url = response.json（）[“images”][0][“url”]

Thank you for your suggestion, we have now updated to support calling sd3

**Comment by suepradun** [comment]
使用sd3测试，一直不成功。 界面提示错误，后台没输出信息。

**Comment by jianghuyihei** [comment]
> 使用sd3测试，一直不成功。 界面提示错误，后台没输出信息。

我是在官方用api调通了代码，但是我在本地调试时会提示我网络错误，我当初认为是网络问题就没有继续解决，这个问题我目前也不太清楚如何解决，你可以看看我的源码，能否提出一些建议。
