### ISSUE TITLE
Suggest: add image-caption generation and automatic insert function.

### ISSUE THREAD

**Issue by luxiangyugo** [DAMO-NLP-SG/WebDesignAgent#2]
The image generation seems unnecessary and costly at the moment (ai painting is not that reliable). 
Let's suppose another workflow:
input: "a brief/detailed description" w/o "images"
output: "a set of website files, easy to deploy"

Thus i suppose the automatic image-caption generation function would be more useful and money-saving. (+ This kind of technique is developed since CLIP from 2021)

**Comment by jianghuyihei** [comment]
Thank you very much for your suggestion, we have updated this feature and hope you can try it.
