### ISSUE TITLE
supporting local LLM？

### ISSUE THREAD

**Issue by xu4wang** [DAMO-NLP-SG/WebDesignAgent#6]
can we use local LLM, for example ollama?

**Comment by xu4wang** [comment]
support codeqwen at least since you are from damoyuan ;-)

**Comment by jianghuyihei** [comment]
> support codeqwen at least since you are from damoyuan ;-)

Yeah, this is our future plan. We will support some other models in the future.  Please look forward to our subsequent updates.

**Comment by jianghuyihei** [comment]
> support codeqwen at least since you are from damoyuan ;-)



> support codeqwen at least since you are from damoyuan ;-)

We found that Qwen-VL does not seem to support asynchronous calls, and it does not support it for the time being.
