### ISSUE TITLE
生成中就錯誤了!! 沒辦法進行...

### ISSUE THREAD

**Issue by labelhigh** [DAMO-NLP-SG/WebDesignAgent#8]
![2024-07-02 17 29 58](https://github.com/DAMO-NLP-SG/WebDesignAgent/assets/1137748/20482589-858a-4633-8cd8-b645d7585eb4)
Error occurred: retryError[<Future at 0x25d3252ff40 state=finished raised OSError>]

CMD畫面顯示資訊
Exception in thread Thread-5 (long_operation):
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\WebDesignAgent\WebDesignAgent\gui.py", line 686, in long_operation
    asyncio.run(self.agent.deal_task_async(need_create_pages))
UnboundLocalError: local variable 'need_create_pages' referenced before assignment
Change Gen IMG to: None
Tailwind
Exception in thread Thread-8 (long_operation):
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\WebDesignAgent\WebDesignAgent\gui.py", line 686, in long_operation
    asyncio.run(self.agent.deal_task_async(need_create_pages))
UnboundLocalError: local variable 'need_create_pages' referenced before assignment
Tailwind

**Comment by jianghuyihei** [comment]
这个看起来是plan的过程中出错了，你把website_img里的网址改成wukong.png（我之前存在了github本地），因为现在直接对网络上的图片进行截图可能会产生问题。

**Comment by jianghuyihei** [comment]
> ![2024-07-02 17 29 58](https://private-user-images.githubusercontent.com/1137748/344965088-20482589-858a-4633-8cd8-b645d7585eb4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTM1MjAsIm5iZiI6MTcxOTkxMzIyMCwicGF0aCI6Ii8xMTM3NzQ4LzM0NDk2NTA4OC0yMDQ4MjU4OS04NThhLTQ2MzMtOGNkOC1iNjQ1ZDc1ODVlYjQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMDk0MDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGQxODgyYmI5Yzg4OGU4MWY4MDNjMTNjZjJmNDA4ZWQ1MTlkOTNmYjE1MmVhMmI0MDlmODBhMmE3YjYzZGEyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u4vyqXqn3ukckRB-HPOOBFRDIO_BWeax-lDmxs2i5ew) Error occurred: retryError[<Future at 0x25d3252ff40 state=finished raised OSError>]
> 
> CMD畫面顯示資訊 Exception in thread Thread-5 (long_operation): Traceback (most recent call last): File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner self.run() File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run self._target(*self._args, **self._kwargs) File "D:\WebDesignAgent\WebDesignAgent\gui.py", line 686, in long_operation asyncio.run(self.agent.deal_task_async(need_create_pages)) UnboundLocalError: local variable 'need_create_pages' referenced before assignment Change Gen IMG to: None Tailwind Exception in thread Thread-8 (long_operation): Traceback (most recent call last): File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner self.run() File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run self._target(*self._args, **self._kwargs) File "D:\WebDesignAgent\WebDesignAgent\gui.py", line 686, in long_operation asyncio.run(self.agent.deal_task_async(need_create_pages)) UnboundLocalError: local variable 'need_create_pages' referenced before assignment Tailwind

这个看起来是plan的过程中出错了，你把website_img里的网址改成wukong.png（我之前存在了github本地），因为现在直接对网络上的图片进行截图可能会产生问题,如果你要对网上图片进行截图的话，可以先用webserver.py，在最下面的函数里将你要的网页地址填进去测试一下能否正常截图
